language: cpp
group: edge
sudo: required
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-7
before-install: CC=gcc-7 && CXX=g++-7
script: ./install-deps.sh && cmake . && make
